version: '3'
services:
  nfvo:
    image: openbaton/nfvo:${OB_VERSION}
    depends_on:
      - rabbitmq_broker
      - nfvo_database
    restart: always
    env_file:
      - env/openbaton.env
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq_broker
      - SPRING_DATASOURCE_URL=jdbc:mysql://nfvo_database:3306/openbaton?useSSL=false
    ports:
      - "8080:8080"
  vnfm_generic:
    image: openbaton/vnfm-generic:${OB_VERSION}
    depends_on:
      - nfvo
    restart: always
    env_file:
      - env/openbaton.env
    environment:
      - RABBITMQ_HOST=rabbitmq_broker
  plugin_vimdriver_openstack_4j:
    image: openbaton/plugin-vimdriver-openstack-4j:${OB_VERSION}
    depends_on:
      - nfvo
    restart: always
    env_file:
      - env/openbaton.env
    environment:
      - RABBITMQ=rabbitmq_broker
  rabbitmq_broker:
    image: rabbitmq:${OB_RABBITMQ_VERSION}
    env_file:
      - env/openbaton.env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./dbdata_rabbit:/var/lib/rabbitmq
  nfvo_database:
    image: mysql/mysql-server:${OB_MYSQL_VERSION}
    env_file:
      - env/openbaton.env
    volumes:
      - ./dbdata_nfvo:/var/lib/mysql
  network_slicing_engine:
    image: openbaton/nse:$OB_NSE_VERSION
    depends_on:
      - nfvo
    env_file:
      - env/openbaton.env
    environment:
      - NFVO_IP=nfvo
      - RABBITMQ_HOST=rabbitmq_broker
volumes:
  dbdata_nfvo:
  dbdata_rabbit:
